// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/expenses.proto

package expensespb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payment struct {
	Date                 int64    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Tags                 []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Amount               float32  `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2084bc508b6b2bcc, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Payment) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Payment) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Payment) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Payment) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Payment) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Category struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Frequency            int32    `protobuf:"varint,3,opt,name=frequency,proto3" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_2084bc508b6b2bcc, []int{1}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Category) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

type Expenses struct {
	Payments             []*Payment `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Expenses) Reset()         { *m = Expenses{} }
func (m *Expenses) String() string { return proto.CompactTextString(m) }
func (*Expenses) ProtoMessage()    {}
func (*Expenses) Descriptor() ([]byte, []int) {
	return fileDescriptor_2084bc508b6b2bcc, []int{2}
}

func (m *Expenses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expenses.Unmarshal(m, b)
}
func (m *Expenses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expenses.Marshal(b, m, deterministic)
}
func (m *Expenses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expenses.Merge(m, src)
}
func (m *Expenses) XXX_Size() int {
	return xxx_messageInfo_Expenses.Size(m)
}
func (m *Expenses) XXX_DiscardUnknown() {
	xxx_messageInfo_Expenses.DiscardUnknown(m)
}

var xxx_messageInfo_Expenses proto.InternalMessageInfo

func (m *Expenses) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

type Categories struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Categories) Reset()         { *m = Categories{} }
func (m *Categories) String() string { return proto.CompactTextString(m) }
func (*Categories) ProtoMessage()    {}
func (*Categories) Descriptor() ([]byte, []int) {
	return fileDescriptor_2084bc508b6b2bcc, []int{3}
}

func (m *Categories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Categories.Unmarshal(m, b)
}
func (m *Categories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Categories.Marshal(b, m, deterministic)
}
func (m *Categories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Categories.Merge(m, src)
}
func (m *Categories) XXX_Size() int {
	return xxx_messageInfo_Categories.Size(m)
}
func (m *Categories) XXX_DiscardUnknown() {
	xxx_messageInfo_Categories.DiscardUnknown(m)
}

var xxx_messageInfo_Categories proto.InternalMessageInfo

func (m *Categories) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type ExpensesRequest struct {
	FromDate             int64    `protobuf:"varint,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate               int64    `protobuf:"varint,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Tag                  string   `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpensesRequest) Reset()         { *m = ExpensesRequest{} }
func (m *ExpensesRequest) String() string { return proto.CompactTextString(m) }
func (*ExpensesRequest) ProtoMessage()    {}
func (*ExpensesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2084bc508b6b2bcc, []int{4}
}

func (m *ExpensesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpensesRequest.Unmarshal(m, b)
}
func (m *ExpensesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpensesRequest.Marshal(b, m, deterministic)
}
func (m *ExpensesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpensesRequest.Merge(m, src)
}
func (m *ExpensesRequest) XXX_Size() int {
	return xxx_messageInfo_ExpensesRequest.Size(m)
}
func (m *ExpensesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpensesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExpensesRequest proto.InternalMessageInfo

func (m *ExpensesRequest) GetFromDate() int64 {
	if m != nil {
		return m.FromDate
	}
	return 0
}

func (m *ExpensesRequest) GetToDate() int64 {
	if m != nil {
		return m.ToDate
	}
	return 0
}

func (m *ExpensesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ExpensesRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type CategoriesRequest struct {
	FromDate             int64    `protobuf:"varint,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate               int64    `protobuf:"varint,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoriesRequest) Reset()         { *m = CategoriesRequest{} }
func (m *CategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*CategoriesRequest) ProtoMessage()    {}
func (*CategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2084bc508b6b2bcc, []int{5}
}

func (m *CategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoriesRequest.Unmarshal(m, b)
}
func (m *CategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoriesRequest.Marshal(b, m, deterministic)
}
func (m *CategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoriesRequest.Merge(m, src)
}
func (m *CategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_CategoriesRequest.Size(m)
}
func (m *CategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoriesRequest proto.InternalMessageInfo

func (m *CategoriesRequest) GetFromDate() int64 {
	if m != nil {
		return m.FromDate
	}
	return 0
}

func (m *CategoriesRequest) GetToDate() int64 {
	if m != nil {
		return m.ToDate
	}
	return 0
}

func (m *CategoriesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*Payment)(nil), "expenses.Payment")
	proto.RegisterType((*Category)(nil), "expenses.Category")
	proto.RegisterType((*Expenses)(nil), "expenses.Expenses")
	proto.RegisterType((*Categories)(nil), "expenses.Categories")
	proto.RegisterType((*ExpensesRequest)(nil), "expenses.ExpensesRequest")
	proto.RegisterType((*CategoriesRequest)(nil), "expenses.CategoriesRequest")
}

func init() { proto.RegisterFile("proto/expenses.proto", fileDescriptor_2084bc508b6b2bcc) }

var fileDescriptor_2084bc508b6b2bcc = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x14, 0xa4, 0x2d, 0x94, 0xf2, 0xf8, 0xfd, 0x54, 0x36, 0x44, 0x2b, 0x78, 0x68, 0xf6, 0xd4, 0x8b,
	0x98, 0xe0, 0xc9, 0x8b, 0x31, 0x8a, 0xe1, 0x6a, 0x56, 0x4f, 0x5e, 0xc8, 0x82, 0x4b, 0xd3, 0xc4,
	0x76, 0x6b, 0xfb, 0x30, 0xf6, 0xe8, 0xa7, 0xf0, 0xeb, 0x9a, 0xdd, 0xfe, 0x8d, 0x78, 0xf5, 0xf6,
	0x66, 0xa6, 0x93, 0x9d, 0x99, 0x14, 0xc6, 0x49, 0x2a, 0x51, 0x5e, 0x88, 0x8f, 0x44, 0xc4, 0x99,
	0xc8, 0x66, 0x1a, 0x12, 0xa7, 0xc2, 0xf4, 0xd3, 0x80, 0xfe, 0x03, 0xcf, 0x23, 0x11, 0x23, 0x21,
	0xd0, 0x7d, 0xe1, 0x28, 0x5c, 0xc3, 0x33, 0x7c, 0x8b, 0xe9, 0x5b, 0x71, 0x98, 0x27, 0xc2, 0x35,
	0x3d, 0xc3, 0x1f, 0x30, 0x7d, 0x2b, 0x6e, 0x9b, 0xca, 0xc8, 0xb5, 0x0a, 0x4e, 0xdd, 0xe4, 0x00,
	0x4c, 0x94, 0x6e, 0x57, 0x33, 0x26, 0x4a, 0xed, 0xe3, 0x41, 0xe6, 0xf6, 0x3c, 0x4b, 0xfb, 0x78,
	0x90, 0x91, 0x63, 0xb0, 0x79, 0x24, 0x77, 0x31, 0xba, 0xb6, 0x67, 0xf8, 0x26, 0x2b, 0x11, 0x7d,
	0x02, 0xe7, 0x8e, 0xa3, 0x08, 0x64, 0x9a, 0x2b, 0x5f, 0xcc, 0xa3, 0x22, 0xc3, 0x80, 0xe9, 0xbb,
	0xe5, 0x33, 0xdb, 0x3e, 0x72, 0x06, 0x83, 0x6d, 0x2a, 0xde, 0x76, 0x22, 0xde, 0xe4, 0x3a, 0x4c,
	0x8f, 0x35, 0x04, 0xbd, 0x02, 0xe7, 0xbe, 0x6c, 0x49, 0xce, 0xc1, 0x49, 0x8a, 0x92, 0x99, 0x6b,
	0x78, 0x96, 0x3f, 0x9c, 0x8f, 0x66, 0xf5, 0x24, 0x65, 0x7d, 0x56, 0x7f, 0x42, 0x6f, 0x00, 0xca,
	0x40, 0xa1, 0xc8, 0xc8, 0x1c, 0x60, 0x53, 0xa3, 0xd2, 0x4e, 0x1a, 0x7b, 0x15, 0x9d, 0xb5, 0xbe,
	0xa2, 0x12, 0x0e, 0xab, 0xc7, 0x99, 0x0a, 0x94, 0x21, 0x99, 0xaa, 0xb4, 0x32, 0x5a, 0xb5, 0x26,
	0x76, 0x14, 0xb1, 0x50, 0x33, 0x9f, 0x40, 0x1f, 0x65, 0x21, 0x99, 0x5a, 0xb2, 0x51, 0x6a, 0x61,
	0x0c, 0xbd, 0xd7, 0x30, 0x0a, 0xb1, 0xec, 0x57, 0x00, 0x72, 0x04, 0x16, 0xf2, 0xa0, 0x9c, 0x5b,
	0x9d, 0x74, 0x05, 0xa3, 0x26, 0xf2, 0x1f, 0x3c, 0x39, 0xff, 0x32, 0x9a, 0x4a, 0x8f, 0x22, 0x7d,
	0x0f, 0x37, 0x82, 0x5c, 0xc3, 0x70, 0x29, 0xb0, 0x5e, 0xf9, 0xb4, 0x19, 0xe5, 0x47, 0xf9, 0x09,
	0xd9, 0x97, 0x68, 0x87, 0x2c, 0xe0, 0xff, 0x52, 0x60, 0x6b, 0xea, 0xe9, 0xde, 0xac, 0x4d, 0x9b,
	0xc9, 0xf8, 0x37, 0x91, 0x76, 0x6e, 0xff, 0x3d, 0x43, 0x25, 0x24, 0xeb, 0xb5, 0xad, 0xff, 0xf0,
	0xcb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0x70, 0x66, 0x54, 0xf9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExpensesServiceClient is the client API for ExpensesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExpensesServiceClient interface {
	GetExpenses(ctx context.Context, in *ExpensesRequest, opts ...grpc.CallOption) (*Expenses, error)
	GetCategories(ctx context.Context, in *CategoriesRequest, opts ...grpc.CallOption) (*Categories, error)
}

type expensesServiceClient struct {
	cc *grpc.ClientConn
}

func NewExpensesServiceClient(cc *grpc.ClientConn) ExpensesServiceClient {
	return &expensesServiceClient{cc}
}

func (c *expensesServiceClient) GetExpenses(ctx context.Context, in *ExpensesRequest, opts ...grpc.CallOption) (*Expenses, error) {
	out := new(Expenses)
	err := c.cc.Invoke(ctx, "/expenses.ExpensesService/GetExpenses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expensesServiceClient) GetCategories(ctx context.Context, in *CategoriesRequest, opts ...grpc.CallOption) (*Categories, error) {
	out := new(Categories)
	err := c.cc.Invoke(ctx, "/expenses.ExpensesService/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExpensesServiceServer is the server API for ExpensesService service.
type ExpensesServiceServer interface {
	GetExpenses(context.Context, *ExpensesRequest) (*Expenses, error)
	GetCategories(context.Context, *CategoriesRequest) (*Categories, error)
}

func RegisterExpensesServiceServer(s *grpc.Server, srv ExpensesServiceServer) {
	s.RegisterService(&_ExpensesService_serviceDesc, srv)
}

func _ExpensesService_GetExpenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpensesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpensesServiceServer).GetExpenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/expenses.ExpensesService/GetExpenses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpensesServiceServer).GetExpenses(ctx, req.(*ExpensesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpensesService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpensesServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/expenses.ExpensesService/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpensesServiceServer).GetCategories(ctx, req.(*CategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExpensesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "expenses.ExpensesService",
	HandlerType: (*ExpensesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExpenses",
			Handler:    _ExpensesService_GetExpenses_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _ExpensesService_GetCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/expenses.proto",
}
